site_name: ReproGen Documentation
site_url: https://your-site-url.com
repo_url: https://github.com/A7med7x7/ReproGen/
theme:
  name: material
  logo: null
  favicon: null
nav:
  - Home: index.md
  - Why ReproGen: why.md
  - Opinions: opinions.md
  - About: about.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
